spring:
  datasource:  # 数据源
    url: jdbc:mysql://192.168.17.128:3306/see_see?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123123

jwt:
  tokenSecret: seeSSSEEE