spring:
  datasource:  # 数据源
    url: jdbc:mysql://192.168.17.128:3306/see_see?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123123
  redis:
    host: 192.168.17.128
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: 30000
  application:
    name: shaobing
#  boot:
#    admin:
#      client:
#        url: http://localhost:8002
#        instance:
#          prefer-ip: true # 有可能会遇到该服务注册到Admin上面之后显示的是 当前计算机用户名:当前服务端口号，把这个改成true之后，就变成 当前服务所在ip:端口号，
#                            # 这样Admin就可以检测这个服务的健康情况了，否则找不到该服务


server:
  servlet:
    context-path: /shaobing

jwt:
  token:
    secret: seeSSSEEE
    timeout: 1800

# management 是所有actuator的配置
# management.endpoints.端口名.xxxx 对某个端点的具体配置
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*' # 以web方式暴露所有端点
#    enabled-by-default: true # 开启所有监控端点
#  endpoint:
#    health:
#      show-details: always #展示详细信息

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl