spring:
  datasource:  # 数据源
    url: jdbc:mysql://192.168.17.128:3306/see_see?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123123
  redis:
    host: 192.168.17.128
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: 30000

server:
  servlet:
    context-path: /shaobing

jwt:
  token:
    secret: seeSSSEEE
    timeout: 600
